#command: docker-compose up -d
version: "3.7"

services:
  db:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASS}"
    ports:
      - ${DB_PORT}:${DB_PORT}
